language: node_js

node_js:
  - "7"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_install:
  - yarn global add truffle

install:
  - yarn install
  - yarn add ethereumjs-testrpc

before_script:
  - testrpc_high_value.sh
  - chmod +x testrpc_high_value.sh

script:
  - truffle test
