language: node_js

node_js:
  - "7"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
  - npm install -g truffle
  - npm install -g ethereumjs-testrpc

before_script:
  - chmod +x testrpc_high_value.sh
  - ./testrpc_high_value.sh

script:
  - truffle test
