language: node_js

node_js:
  - "7"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
  - npm install -g ethereumjs-testrpc
  - npm install -g truffle@^4.0.0-beta.2
  - npm install

script:
  - ./testrpc_high_value.sh & truffle test
